lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
